# Generated by Django 3.2.7 on 2021-09-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank='none.png', upload_to='acc/%y/%m'),
        ),
    ]
