# Generated by Django 3.2.7 on 2021-10-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_alter_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, upload_to='acc/%y/%m'),
        ),
    ]
